apiVersion: v1
kind: Namespace
metadata:
  name: local-path-provisioner
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/rancher/local-path-provisioner.git
  ref:
    tag: v0.0.33
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: local-path-provisioner
spec:
  interval: 10m
  chart:
    spec:
      chart: ./deploy/chart/local-path-provisioner
      sourceRef:
        kind: GitRepository
        name: local-path-provisioner
        namespace: flux-system
      interval: 10m
  values:
    storageClass:
      defaultClass: true
