apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: action-runner-controller-operator
    app.kubernetes.io/part-of: action-runner-controller
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/version: 0.13.0
  name: arc-systems
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gha-runner-scale-set-controller
  namespace: flux-system
  labels:
    app.kubernetes.io/name: action-runner-controller-operator
    app.kubernetes.io/part-of: action-runner-controller
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/version: 0.13.0
name: gha-runner-scale-set-controller
spec:
  interval: 5m
url: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
ref:
  semver: 0.13.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set-controller
  namespace: arc-systems
  labels:
    app.kubernetes.io/name: action-runner-controller-operator
    app.kubernetes.io/part-of: action-runner-controller
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/version: 0.13.0
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set-controller
    namespace: flux-system
